### ISSUE TITLE
Parameter order for GTR model

### ISSUE THREAD

**Issue by adrienlemeur** [lucasnell/jackalope#16]
Hello,
I am trying to mutate a fasta sequence using a GTR model, but I can not figure out the abcdef parameter order. The vignette("sub-models") gives an indication but I am not familiar with the notation. I got the A -> T, A -> C, etc. rates with IQtree model finder, it should be good right ?
Thanks ~
Adrien

**Comment by adrienlemeur** [comment]
went with : 
c(GTR$mut$C_T, GTR$mut$A_T, GTR$mut$G_T, GTR$mut$A_C, GTR$mut$C_G, GTR$mut$A_G)
but the resulting substitution rate matrix is not what I expected ?

**Comment by lucasnell** [comment]
Hi Adrien,
The parameter order follows [Yang (2006)](https://global.oup.com/academic/product/computational-molecular-evolution-9780198567028?lang=es&cc=gb), so the matrix rows and columns are ordered T, C, A, then G. The vignette is not rendering matrices properly on my computer, but the online documentation ([link](https://lucasnell.github.io/jackalope/articles/sub-models.html)) seems to be rendering okay.

The order you're using looks good. I've never used ModelFinder, but perhaps the difference you're seeing is because the parameters `a`, `b`, ...,`f` get multiplied by the allele frequencies? (The first column get multiplied by $\pi_T$, second by $\pi_C$, etc.)

**Comment by adrienlemeur** [comment]
Oh thank you very much, indeed the vignette in R studio was rendered as a single line.
I have made a mistake when calculating the parameters, but I should be fine now.
Thank you very much !
